# -*- coding: utf-8 -*-
"""rectangle_numbering

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VhtGFbhbw3k7WysCs_DF0p-6BZ4IAmat

**TASK 1**
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

"""Read Image"""

image = cv2.imread("/content/rect.png")
gray_scaled = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(gray_scaled,200,255,cv2.THRESH_BINARY)  
contours = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
contours = contours[0] if len(contours) == 2 else contours[1]
width = 3
color = (200,100,200)
print(len(contours))

"""Measuring length of line"""

inner_lines_contour = []
for i in range(3,len(contours),3):
    print(i)
    inner_lines_contour.append(contours[i])

for i in range(len(inner_lines_contour)):
    cv2.drawContours(image, inner_lines_contour[i], -1, color , width)

"""Assigning numbers to the lines"""

inner_lines_contour = []
for i in range(3,len(contours),3):
    print(i)
    inner_lines_contour.append(contours[i])

for i in range(len(inner_lines_contour)):
    cv2.drawContours(image, inner_lines_contour[i], -1, color , width)
  

# sorted_lines_inside_rectangle = sorted(inner_lines_contour, key=cv2.contourArea)

# for i, cont in (sorted_lines_inside_rectangle[:4],1):
#     cv2.putText(image, str(i), (cont[0,0,0], cont[0,0,1]-10), cv2.FONT_HERSHEY_SIMPLEX, 1.4, (240,100,100),4)

plt.figure(figsize=[10,7])
plt.imshow(image)


for i in range(len(inner_lines_contour)):
    print('arcLength:', cv2.arcLength(inner_lines_contour[i], True))

for i in range(len(inner_lines_contour)):
    if cv2.arcLength(inner_lines_contour[i], True) == 165.48022890090942:
        cv2.putText(image, str(1),(400,300), cv2.FONT_HERSHEY_COMPLEX, 1.3, (0,200,0), 2)
    
    if cv2.arcLength(inner_lines_contour[i], True) == 171.39696860313416:
        cv2.putText(image, str(2),(100,50), cv2.FONT_HERSHEY_COMPLEX, 1.3, (0,200,0), 2)
    
    if cv2.arcLength(inner_lines_contour[i], True) == 254.5096664428711:
        cv2.putText(image, str(3), (400,50), cv2.FONT_HERSHEY_COMPLEX, 1.3, (0,200,0), 2)
    
    if cv2.arcLength(inner_lines_contour[i], True) == 338.6173119544983:
        cv2.putText(image, str(4), (100,300), cv2.FONT_HERSHEY_COMPLEX, 1.3, (0,200,0), 2)



plt.figure(figsize=[10,7])
plt.imshow(image)
plt.show()

